# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-27 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_lista_peliculas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lista_Peliculas',
            new_name='ListaPeliculas',
        ),
        migrations.AddField(
            model_name='lista',
            name='peliculas',
            field=models.ManyToManyField(to='movies.ListaPeliculas'),
        ),
    ]
