# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-27 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20160627_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista',
            name='peliculas',
        ),
        migrations.AddField(
            model_name='listapeliculas',
            name='lista',
            field=models.ManyToManyField(to='movies.Lista'),
        ),
    ]
